"""add insights and insight_evidence tables

Revision ID: 17575d5d134e
Revises: 0227886c3e78
Create Date: 2026-07-18 15:45:00.417511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17575d5d134e'
down_revision: Union[str, Sequence[str], None] = '0227886c3e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_project_id'), 'insights', ['project_id'], unique=False)
    op.create_table('insight_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_id', 'segment_id', name='uq_insight_segment')
    )
    op.create_index(op.f('ix_insight_evidence_insight_id'), 'insight_evidence', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_evidence_segment_id'), 'insight_evidence', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_evidence_segment_id'), table_name='insight_evidence')
    op.drop_index(op.f('ix_insight_evidence_insight_id'), table_name='insight_evidence')
    op.drop_table('insight_evidence')
    op.drop_index(op.f('ix_insights_project_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
