"""add PAT and clipped evidence

Revision ID: 84d18aca2c3e
Revises: f7792e18c264
Create Date: 2026-07-20 15:45:48.723125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d18aca2c3e'
down_revision: Union[str, Sequence[str], None] = 'f7792e18c264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipped_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipped_evidence_project_id'), 'clipped_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_clipped_evidence_user_id'), 'clipped_evidence', ['user_id'], unique=False)
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False)
    op.add_column('insight_evidence', sa.Column('clip_id', sa.UUID(), nullable=True))
    op.alter_column('insight_evidence', 'segment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_insight_evidence_clip_id'), 'insight_evidence', ['clip_id'], unique=False)
    op.create_unique_constraint('uq_insight_clip', 'insight_evidence', ['insight_id', 'clip_id'])
    op.create_foreign_key(None, 'insight_evidence', 'clipped_evidence', ['clip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insight_evidence', type_='foreignkey')
    op.drop_constraint('uq_insight_clip', 'insight_evidence', type_='unique')
    op.drop_index(op.f('ix_insight_evidence_clip_id'), table_name='insight_evidence')
    op.alter_column('insight_evidence', 'segment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('insight_evidence', 'clip_id')
    op.drop_index(op.f('ix_personal_access_tokens_user_id'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_index(op.f('ix_clipped_evidence_user_id'), table_name='clipped_evidence')
    op.drop_index(op.f('ix_clipped_evidence_project_id'), table_name='clipped_evidence')
    op.drop_table('clipped_evidence')
    # ### end Alembic commands ###
