"""Add PIIDetection table

Revision ID: a5d82dc804f6
Revises: 17575d5d134e
Create Date: 2026-07-18 16:05:54.594424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d82dc804f6'
down_revision: Union[str, Sequence[str], None] = '17575d5d134e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_detections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('segment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_detections_segment_id'), 'pii_detections', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pii_detections_segment_id'), table_name='pii_detections')
    op.drop_table('pii_detections')
    # ### end Alembic commands ###
