"""Add word_timestamps to transcript_segments

Revision ID: b97db99c6a2c
Revises: a5d82dc804f6
Create Date: 2026-07-20 00:01:14.649295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b97db99c6a2c'
down_revision: Union[str, Sequence[str], None] = 'a5d82dc804f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_segments', sa.Column('word_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_segments', 'word_timestamps')
    # ### end Alembic commands ###
