"""remove fk from audit_logs to recordings

Revision ID: f2e29fba727d
Revises: 97543d7eedb6
Create Date: 2026-07-20 12:58:17.097735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e29fba727d'
down_revision: Union[str, Sequence[str], None] = '97543d7eedb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_recording_id_fkey'), 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('audit_logs_recording_id_fkey'), 'audit_logs', 'recordings', ['recording_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
