"""Add review_status to pii_detections

Revision ID: f45f4ad32064
Revises: b97db99c6a2c
Create Date: 2026-07-20 12:29:33.441848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45f4ad32064'
down_revision: Union[str, Sequence[str], None] = 'b97db99c6a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first so existing rows don't violate NOT NULL
    op.add_column('pii_detections', sa.Column(
        'review_status', sa.Text(), nullable=True,
        comment='pending | confirmed | dismissed'
    ))
    op.add_column('pii_detections', sa.Column(
        'reviewed_by', sa.UUID(as_uuid=False), nullable=True,
        comment='user_id of the editor who confirmed or dismissed this detection'
    ))
    # Backfill existing rows
    op.execute("UPDATE pii_detections SET review_status = 'pending' WHERE review_status IS NULL")
    # Now enforce NOT NULL and add check constraint
    op.alter_column('pii_detections', 'review_status', nullable=False)
    op.create_check_constraint(
        'pii_detections_review_status_check',
        'pii_detections',
        "review_status IN ('pending', 'confirmed', 'dismissed')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pii_detections', 'reviewed_by')
    op.drop_column('pii_detections', 'review_status')
    # ### end Alembic commands ###
