"""add consent fields to recordings

Revision ID: f7792e18c264
Revises: 2f6bed8f760a
Create Date: 2026-07-20 15:38:13.278637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7792e18c264'
down_revision: Union[str, Sequence[str], None] = '2f6bed8f760a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('consent_recording', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('recordings', sa.Column('consent_external_sharing', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('recordings', sa.Column('consent_ai_processing', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'consent_ai_processing')
    op.drop_column('recordings', 'consent_external_sharing')
    op.drop_column('recordings', 'consent_recording')
    # ### end Alembic commands ###
