"""add_ai_tag_suggestions

Revision ID: f9d7606365e8
Revises: 84d18aca2c3e
Create Date: 2026-07-20 17:12:05.630930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d7606365e8'
down_revision: Union[str, Sequence[str], None] = '84d18aca2c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tag_suggestions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('segment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('suggested_name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tag_suggestions_project_id'), 'ai_tag_suggestions', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_tag_suggestions_segment_id'), 'ai_tag_suggestions', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tag_suggestions_segment_id'), table_name='ai_tag_suggestions')
    op.drop_index(op.f('ix_ai_tag_suggestions_project_id'), table_name='ai_tag_suggestions')
    op.drop_table('ai_tag_suggestions')
    # ### end Alembic commands ###
